### ISSUE TITLE
题目模块相关设计

### ISSUE THREAD

**Issue by dianhsu** [4ddl/ddlb#2]
## 以此为准

| 键 | 信息 |
| --- | --- | 
| `id` | 编号 |
| `title` | 标题 |
| `content` | 题目的内容 |
| `time_limit`| 时间限制，单位MS |
| `memory_limit` | 内存限制, 单位MB |
| `special_judge` | SPJ |
| `public` | 0:允许提交和查看;1:允许查看;2:不允许提交和查看 |
| `create_time` | 创建时间 |
| `last_update` | 上次修改时间 |
| `source` | 来源 |
| `author` | 作者，指上传者 |
| `manifest` | 测试样例和相关文件等 |

> 题目内显示的样例是不会被执行

manifest:
```json
{
    "hash": "27382783126378263781997548935798",
    "spj": true,
    "spj_code": "#include <bits/stdc++.h>\n",
    "test_cases": [{"in":"1231231","out":"123123"},{"in":"1231231","out":"123123"}]

}
```

**Comment by WUST-mengqinyu** [comment]
| 键                 | 信息                                       |
| ------------------ | ------------------------------------------ |
| source             | 题目来源                                   |
| ac_number          | 通过数                                     |
| submit_number      | 提交数                                     |
| create_time        | 创建时间                                   |
| update_time        | 上次修改时间                               |
| allow_submit       | 允许提交（没有数据，或者只允许看题的场景） |
| tags               | json格式保存所有tag                        |
| allow_lauguage     | 允许提交的语言                             |
| level              | 题目难度                                   |
| correct_submission | 标程的提交号                               |

**Comment by dianhsu** [comment]
题目接口权限表
| Group | List | Retrieve | Create | Update | Delete |
| --- | --- | --- | --- | --- | --- |
| Administrator | Yes | Yes | Yes | Yes | Yes |
| Authenticated | Public or owned | Public or owned | No | No | Owned | 
| Anonymous | Public | Public | No | No | No |
| `creator` | Public or owned | Public or owned | Yes | Owned | Owned |
